/**
 * build-graph.mjs — Parce Brain
 * Builds graph.json + brain.html + patches ## Related (auto) in memory files.
 * Run: node skills/brain/build-graph.mjs
 *
 * Memory dir resolution: env MEMORY_DIR > <repo>/memory (relative to this script).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const MEMORY_DIR = process.env.MEMORY_DIR || path.resolve(SCRIPT_DIR, '../../memory');
const GRAPH_OUT  = MEMORY_DIR + '/graph.json';
const HTML_OUT   = MEMORY_DIR + '/brain.html';
const EXCLUDE    = new Set(['MEMORY.md', '_template.md', 'graph.json', 'brain.html']);
const MARKER     = '<!-- generated by brain rebuild, do not edit -->';
const MIN_WEIGHT = 0.25;

// English + Portuguese + Spanish stopwords — trim or extend for your language.
const STOP = new Set(('the and or in of to a is for on with not be have do that this it its we our they their are was were will can may also from when where how what which an by all but if so at up out one has had been there then than too only after over before through while yet both off down via per use new get set any each few well just like make now back next last first many much more most some still even already always never ever often ' +
  'a o e de do da em um uma para por com que nao não se mais mas tambem também ja já no na ao as os das dos ser ter ver fazer ele ela eles elas seu sua este esta todos todas entre sobre como quando ' +
  'el la los las un una unas unos y es son fue para por con del al lo le se su sus este esta esto ese esa eso mas más pero como cuando donde').split(/\s+/));

function parseFrontmatter(raw) {
  const result = { name: '', type: '', tags: [], body: '' };
  const lines  = raw.split('\n');
  let i = 0, inFm = false;
  if (lines[0]?.trim() === '---') { inFm = true; i = 1; }
  const bodyLines = [];
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (inFm && line.trim() === '---') { inFm = false; continue; }
    if (inFm) {
      // accepts top-level and indented keys (e.g. `type` nested under `metadata:`)
      const m = line.match(/^\s*(\w+):\s*(.*)$/);
      if (m) {
        const [, k, v] = m;
        if (k === 'name') result.name = v.trim();
        if (k === 'type') result.type = v.trim();
        if (k === 'tags') result.tags = v.replace(/[\[\]]/g, '').split(',').map(t => t.trim()).filter(Boolean);
      }
    } else { bodyLines.push(line); }
  }
  result.body = bodyLines.join('\n').trim();
  return result;
}

function extractLinks(content) {
  const links = new Set();
  // markdown: [txt](file.md) -> id (filename)
  for (const m of content.matchAll(/\[([^\]]+)\]\(([^)]+\.md)\)/g))
    links.add(path.basename(m[2], '.md'));
  // wikilink: [[slug]] -> slug (resolved to id via name in main())
  for (const m of content.matchAll(/\[\[([^\]]+)\]\]/g))
    links.add(m[1].trim());
  return links;
}

function tokenize(text) {
  return text.toLowerCase().replace(/[^\w\s]/g, ' ').split(/\s+/)
    .filter(t => t.length >= 3 && !STOP.has(t) && !/^\d+$/.test(t));
}

function buildTFIDF(docs) {
  const N = docs.length, df = new Map();
  for (const { tokens } of docs) for (const t of new Set(tokens)) df.set(t, (df.get(t) || 0) + 1);
  const idf = new Map();
  for (const [t, d] of df) idf.set(t, Math.log(1 + N / (1 + d)));
  const vectors = new Map();
  for (const { id, tokens } of docs) {
    const tf = new Map();
    for (const t of tokens) tf.set(t, (tf.get(t) || 0) + 1);
    const total = Math.max(tokens.length, 1), vec = new Map();
    for (const [t, c] of tf) { const w = (c / total) * (idf.get(t) || 0); if (w > 0) vec.set(t, w); }
    vectors.set(id, vec);
  }
  return vectors;
}

function cosine(v1, v2) {
  if (!v1 || !v2) return 0;
  let dot = 0, n1 = 0, n2 = 0;
  for (const [t, w] of v1) { dot += w * (v2.get(t) || 0); n1 += w * w; }
  for (const [, w] of v2) n2 += w * w;
  const denom = Math.sqrt(n1) * Math.sqrt(n2);
  return denom > 0 ? dot / denom : 0;
}

function getPrefix(id) { const i = id.search(/[-_]/); return i > 0 ? id.slice(0, i) : null; }

function patchRelated(filePath, top3) {
  const raw = fs.readFileSync(filePath, 'utf8');
  const section = '\n\n## Related (auto)\n' +
    top3.map(({ id, weight }) => `- [${id}.md](${id}.md) -- ${weight.toFixed(2)}`).join('\n') +
    '\n' + MARKER;
  const relIdx = raw.indexOf('\n## Related (auto)');
  let updated;
  if (relIdx !== -1) {
    const markerIdx = raw.indexOf(MARKER, relIdx);
    if (markerIdx !== -1) {
      if (raw.slice(relIdx, markerIdx + MARKER.length) === section) return false;
      updated = raw.slice(0, relIdx) + section;
    } else { updated = raw.slice(0, relIdx) + section; }
  } else { updated = raw.trimEnd() + section; }
  fs.writeFileSync(filePath, updated, 'utf8');
  return true;
}

function generateHTML(graph) {
  const tmplPath = new URL('./brain-template.html', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1');
  let tmpl = fs.readFileSync(tmplPath, 'utf8');
  const safeJson = JSON.stringify(graph).replace(/<\/script>/gi, '<\\/script>');
  return tmpl.replace('/*{{GRAPH_DATA}}*/', safeJson);
}

async function main() {
  const entries = fs.readdirSync(MEMORY_DIR, { withFileTypes: true });
  const files   = entries.filter(e => e.isFile() && e.name.endsWith('.md') && !EXCLUDE.has(e.name)).map(e => e.name);
  console.log('Found ' + files.length + ' memory files');

  const memories = files.map(f => {
    const raw      = fs.readFileSync(path.join(MEMORY_DIR, f), 'utf8');
    const id       = f.replace('.md', '');
    const parsed   = parseFrontmatter(raw);
    const links    = extractLinks(raw);
    const bodyClean = parsed.body.replace(/\n## Related \(auto\)[\s\S]*$/, '').trim();
    const tokens   = tokenize((parsed.name || id) + ' ' + (parsed.tags || []).join(' ') + ' ' + bodyClean);
    return { id, file: f, ...parsed, body: bodyClean, links, tokens };
  });

  const memMdRaw = fs.readFileSync(path.join(MEMORY_DIR, 'MEMORY.md'), 'utf8');
  const idSet    = new Set(memories.map(m => m.id));

  // resolve links (markdown=id, wikilink=slug/name) to canonical ids (filename)
  const nameToId = new Map(memories.filter(m => m.name).map(m => [m.name, m.id]));
  for (const m of memories) {
    const resolved = new Set();
    for (const l of m.links) {
      if (idSet.has(l)) resolved.add(l);
      else if (nameToId.has(l)) resolved.add(nameToId.get(l));
    }
    m.links = resolved;
  }

  const memMdSections = memMdRaw.split(/^## /m).slice(1)
    .map(s => [...extractLinks(s)].filter(l => idSet.has(l)));
  const coSection = new Map();
  for (const sec of memMdSections)
    for (let i = 0; i < sec.length; i++)
      for (let j = i + 1; j < sec.length; j++)
        coSection.set([sec[i], sec[j]].sort().join('|'), true);

  const tfidf = buildTFIDF(memories.map(m => ({ id: m.id, tokens: m.tokens })));

  const rawEdges = [];
  for (let i = 0; i < memories.length; i++) {
    for (let j = i + 1; j < memories.length; j++) {
      const a = memories[i], b = memories[j];
      let w = 0;
      if (a.links.has(b.id) || b.links.has(a.id))             w += 1.0;
      if (coSection.has([a.id, b.id].sort().join('|')))        w += 0.7;
      const pa = getPrefix(a.id), pb = getPrefix(b.id);
      if (pa && pb && pa === pb)                               w += 0.6;
      const st = (a.tags || []).filter(t => (b.tags || []).includes(t)).length;
      if (st > 0) w += Math.min(st * 0.2, 0.8);
      if (a.type && b.type && a.type === b.type)              w += 0.1;
      const sim = cosine(tfidf.get(a.id), tfidf.get(b.id));
      if (sim > 0.05) w += sim * 0.5;
      if (w > 0) rawEdges.push({ from: a.id, to: b.id, raw: w });
    }
  }

  const maxW  = Math.max(...rawEdges.map(e => e.raw), 1);
  const edges = rawEdges.map(e => ({ from: e.from, to: e.to, weight: e.raw / maxW }))
    .filter(e => e.weight >= MIN_WEIGHT).sort((a, b) => b.weight - a.weight);
  console.log('Computed ' + edges.length + ' edges (raw: ' + rawEdges.length + ')');

  const degree    = new Map(memories.map(m => [m.id, 0]));
  const adjacency = new Map(memories.map(m => [m.id, []]));
  for (const e of edges) {
    degree.set(e.from, degree.get(e.from) + 1);
    degree.set(e.to,   degree.get(e.to) + 1);
    adjacency.get(e.from)?.push({ id: e.to,   weight: e.weight });
    adjacency.get(e.to)?.push  ({ id: e.from, weight: e.weight });
  }
  const maxDeg = Math.max(...degree.values(), 1);

  const graphNodes = memories.map(m => ({
    id: m.id, file: m.file, title: m.name || m.id, type: m.type || 'unknown',
    tags: m.tags || [], degree: degree.get(m.id),
    centrality: parseFloat((degree.get(m.id) / maxDeg).toFixed(3)), body: m.body,
  }));

  const avgWeight = edges.length > 0
    ? (edges.reduce((s, e) => s + e.weight, 0) / edges.length).toFixed(3) : '0';

  const graph = {
    generated_at: new Date().toISOString(),
    stats: { nodes: graphNodes.length, edges: edges.length, avg_weight: avgWeight },
    nodes: graphNodes,
    edges: edges.map(e => ({ from: e.from, to: e.to, weight: parseFloat(e.weight.toFixed(3)) })),
  };

  fs.writeFileSync(GRAPH_OUT, JSON.stringify(graph, null, 2), 'utf8');
  console.log('graph.json: ' + graphNodes.length + ' nodes, ' + edges.length + ' edges, avg ' + avgWeight);

  let patched = 0;
  for (const m of memories) {
    const neighbors = (adjacency.get(m.id) || []).sort((a, b) => b.weight - a.weight).slice(0, 3);
    if (neighbors.length === 0) continue;
    if (patchRelated(path.join(MEMORY_DIR, m.file), neighbors)) patched++;
  }
  console.log('Patched ' + patched + ' files with Related (auto)');

  fs.writeFileSync(HTML_OUT, generateHTML(graph), 'utf8');
  console.log('brain.html written\n');

  const top5 = [...graphNodes].sort((a, b) => b.degree - a.degree).slice(0, 5);
  console.log('Top 5 by connections:');
  for (const n of top5) console.log('  ' + String(n.degree).padStart(3) + ' -- ' + n.id + ' (' + n.type + ')');
}

main().catch(e => { console.error('Error:', e.message); process.exit(1); });
